feat: add obtaining  SAToken functionality from auth
fabric8-services/fabric8-common pull request #56
Opened 2018-10-31 14:08 UTC by dipak-pawar

**Changes Proposed in this PR**
* add getting Sa token functionality using clientID and secret by calling auth, so any service can use it.

2018-10-31 22:23 UTC, alexeykazakov requested changes
Looks good! Just some minor comments.

2018-10-31 22:23 UTC, alexeykazakov commented on Gopkg.lock
> -  digest = "1:2aff5edb9bccd2974090fddb17ca7ab05a3f5c983db567c30c7f0b53404f5783"
What version of dep are you using? Please install the latest v0.5.0.

2018-10-31 22:23 UTC, alexeykazakov commented on httpsupport/http_client.go
> +func RemoveTrailingSlashToURL(url string) string {
`RemoveTrailingSlashFromURL()`
Also please fix the comment.

2018-10-31 22:23 UTC, alexeykazakov commented on httpsupport/url_blackbox_test.go
> +func TestRemoveTrailingSlashToURLSuccess(t *testing.T) {
`TestRemoveTrailingSlashFromURLSuccess()`

2018-10-31 22:23 UTC, alexeykazakov commented on token/token.go
> +type Configuration interface {
Let's maybe call it `AuthSrvConfiguration` or something like that?

2018-10-31 22:23 UTC, alexeykazakov commented on token/token.go
> +func ServiceAccountToken(ctx context.Context, config Configuration, clientID, clientSecret string, options ...httpsupport.HTTPClientOption) (token string, err error) {
Don't use named return values. So, instead of `ServiceAccountToken(...) (token string, err error)` use just `ServiceAccountToken(...) (string, error)`. It's less error prone.

2018-10-31 22:23 UTC, alexeykazakov commented on token/token.go
> +	res, err := client.ExchangeToken(ctx, path, payload, contentType)
We should also try to forward RequestID if present in the context - https://github.com/fabric8-services/fabric8-common/blob/9dec25ad62353f147cf1ee7e1dd294167e36bfb9/goasupport/forward_requestid.go#L10
```
res, err := client.ExchangeToken(goasupport.ForwardContextRequestID(ctx), path, payload, contentType)
```

2018-10-31 22:23 UTC, alexeykazakov commented on token/token.go
> +	defer func() {
Or just `defer httpsupport.CloseResponse(res)`

2018-10-31 22:23 UTC, alexeykazakov commented on token/token_blackbox_test.go
> +		assert.NotEmpty(t, token)
Check if the token has expected value.

2018-10-31 22:23 UTC, alexeykazakov commented on token/token_blackbox_test.go
> +		require.Error(t, err)
Check the error message too. So, you can make sure you got the expected error and not something else.

2018-10-31 22:23 UTC, alexeykazakov commented on token/token_blackbox_test.go
> +		require.Error(t, err)
Check the error message.

2018-10-31 22:23 UTC, alexeykazakov commented on token/token_blackbox_test.go
> +		require.Error(t, err)
Check the error message.

2018-10-31 22:23 UTC, alexeykazakov commented on token/token_blackbox_test.go
> +	})
Auth can also return 401 (if credentials are wrong). Please add a test for that too.

2018-11-01 05:16 UTC, dipak-pawar commented on Gopkg.lock
> -  digest = "1:2aff5edb9bccd2974090fddb17ca7ab05a3f5c983db567c30c7f0b53404f5783"
I am using `v0.4.1`. Let me update it to latest

2018-11-01 07:12 UTC, dipak-pawar commented on token/token.go
> +	res, err := client.ExchangeToken(ctx, path, payload, contentType)
thnx for pointers. I will add it

2018-11-12 06:51 UTC, dipak-pawar commented
@alexeykazakov, I have addressed your review comments. Please have a look.

2018-11-12 07:15 UTC, alexeykazakov approved these changes

2018-11-12 10:09 UTC, merged